# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  run_tests_export:
    working_directory: ~/espnet_onnx
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: sudo apt-get -y update; sudo apt-get install libsndfile1
      - run: pip install --upgrade pip
      - run: pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113
      - run: pip install -r tools/requirements_export.txt
      - run: pip install pytest
      - run: wget https://github.com/Masao-Someki/espnet_onnx/releases/download/custom_ort_v1.11.1-espnet_onnx/onnxruntime-1.11.1_espnet_onnx-cp38-cp38-linux_x86_64.whl
      - run: pip install onnxruntime-1.11.1_espnet_onnx-cp38-cp38-linux_x86_64.whl
      - run: pytest tests --config_dir tests/test_config

workflows:
  build_and_test:
    jobs:
      - run_tests_export
